version: '3.1'

networks:
  back_network:
  driver: bridge

services:
  a_web:
    build:
      context: ./a_web
    ports:
      - "80:80"
    volumes:
      - ./a_db/logs:/var/log/nginx
    depends_on:
      - a_app
  a_app:
    build:
      context: ./a_app
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"  #exponer el puerto para el contenedor nginx
    volumes:
      - ./a_app:/a_app
    networks:
      - back_network
